### ISSUE TITLE
Home button and power button not working

### ISSUE THREAD

**Issue by masagrator** [XorTroll/LogManager-reimpl#2]
When this sysmodule is running, home button and power button are not detected by OS. Deleting LogManager brings back those buttons.

I have compiled it with libnx dbc4b75

Atmosphere 0.12.0, fusee-primary
FW 10.0.1

Deleted all additional sysmodules I am using, still happening.

**Comment by XorTroll** [comment]
Yeah, it's quite a weird problem
I literally have no clue why this happens, is the only issue I've found yet :P

**Comment by XorTroll** [comment]
Last commit fixes it ;)

**Comment by masagrator** [comment]
I think by mistake you have deleted root makefile. :P 

And it's working. Thanks. :)
